# Generated by Django 4.1.3 on 2022-12-06 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_subject_remove_question_pub_date_question_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.CharField(max_length=200, verbose_name='Question'),
        ),
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.IntegerField(choices=[(0, 'Single Answer'), (1, 'Multi Answer')], default=0, verbose_name='Quiz Type'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_text',
            field=models.CharField(max_length=100, verbose_name='Quiz Subject'),
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('options', models.IntegerField(choices=[(1, 'A'), (2, 'B'), (3, 'C'), (4, 'D')], verbose_name='Option: ABCD')),
                ('content', models.CharField(max_length=256, verbose_name='选项内容')),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.question')),
            ],
        ),
    ]
