# Generated by Django 4.1.3 on 2022-12-06 12:44

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_option_title_alter_option_optiona_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='option',
            name='title',
        ),
        migrations.AddField(
            model_name='option',
            name='answer',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], default='', max_length=9, verbose_name='Quiz Answer'),
        ),
        migrations.AlterField(
            model_name='option',
            name='optionA',
            field=models.CharField(default=None, max_length=40, verbose_name='A'),
        ),
        migrations.AlterField(
            model_name='option',
            name='optionB',
            field=models.CharField(default=None, max_length=40, verbose_name='B'),
        ),
        migrations.AlterField(
            model_name='option',
            name='optionC',
            field=models.CharField(default=None, max_length=40, verbose_name='C'),
        ),
        migrations.AlterField(
            model_name='option',
            name='optionD',
            field=models.CharField(default=None, max_length=40, verbose_name='D'),
        ),
    ]
