# Generated by Django 4.1.3 on 2022-12-06 14:03

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_remove_option_title_option_answer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultiQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(0, 'Single Answer'), (1, 'Multi Answer')], default=0, verbose_name='Quiz Type')),
                ('question_text', models.CharField(max_length=200, verbose_name='Question')),
                ('optionA', models.CharField(default=None, max_length=40, verbose_name='A')),
                ('optionB', models.CharField(default=None, max_length=40, verbose_name='B')),
                ('optionC', models.CharField(default=None, max_length=40, verbose_name='C')),
                ('optionD', models.CharField(default=None, max_length=40, verbose_name='D')),
                ('answer', multiselectfield.db.fields.MultiSelectField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], default='', max_length=9, verbose_name='Quiz Answer')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.subject')),
            ],
        ),
        migrations.RemoveField(
            model_name='question',
            name='category',
        ),
        migrations.DeleteModel(
            name='Option',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
