# Generated by Django 4.1.3 on 2022-12-06 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_multiquestion_remove_question_category_delete_option_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='multiquestion',
            name='point',
            field=models.IntegerField(default=0, verbose_name='Point'),
        ),
    ]
