# Generated by Django 4.1.3 on 2022-12-07 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_multiquestion_point'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200, verbose_name='Student Name')),
                ('age', models.IntegerField(default=0, verbose_name='Student Age')),
                ('gender', models.CharField(choices=[('female', 'female'), ('male', 'male')], default='female', max_length=100, verbose_name='Student Gender')),
            ],
        ),
    ]
