# Generated by Django 4.1.3 on 2022-12-07 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0010_remove_student_id_student_pwd_student_sid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='pwd',
            field=models.CharField(default=None, max_length=20, verbose_name='Password'),
        ),
    ]
